[package]
name = "test"
edition = "2024"
version = "0.1.0" 

[dependencies]
apostasy = { version = "0.1.0", path = "apostasy" }
apostasy-macros = { version = "0.1.0", path = "apostasy/apostasy-macros" }
linkme = "0.3.35"
