[package]
name = "apostasy-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "apostasy_macros"
path = "src/lib.rs"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
linkme = "0.3"
